name: Deploy to Slatwall contentful Space
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.SLATWALL_SHARED_PAT }}" >> .npmrc
        name: add auth token for package pull
      - run: |
          echo "CONTENTFUL_ORG_ID=${{ secrets.CONTENTFUL_ORG_ID }}" >> .env.local
          echo "CONTENTFUL_APP_DEF_ID=${{ secrets.CONTENTFUL_APP_DEF_ID }}" >> .env.local
          echo "CONTENTFUL_ACCESS_TOKEN=${{ secrets.CONTENTFUL_ACCESS_TOKEN }}" >> .env.local
        name: Add deployment Keys
      - run: |
          npm install
          npm run build
          npm run upload-ci
        name: Build and Deploy
